
server:
  port: 8903

spring:
  application:
    name: sentinel
  cloud:
    sentinel:
      transport:
        dashboard: 10.16.0.23:8082
      #用在这配置数据源的模式与本地SPI冲突  SPI优先 使用数据源就不能使用SPI 想测数据源可以将resource中的那个SPI扩展文件换个路径让SPI失效
      #要想同时生效需要再SPI里去注册数据源
      #从控制台修改规则并不会改数据源里的数据，如果要实现这个功能需要修改控制台代码 https://github.com/alibaba/Sentinel/wiki/Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%EF%BC%88%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7%E7%AE%A1%E7%90%86%EF%BC%89#%E8%A7%84%E5%88%99%E9%85%8D%E7%BD%AE
      datasource:
        - nacos:
            server-addr: 10.16.0.21:8848,10.16.0.22:8848,10.16.0.23:8848
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow


